_wandb:
    value:
        cli_version: 0.23.0
        e:
            vak1wl51xj58rdkyto11gecalprkyl36:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "11811160064"
                codePath: /Users/akashdhadiwal/Downloads/IE7374/IE7374-MLOps/Labs/Experiment_Tracking_Labs/W&B/copy.ipynb
                codePathLocal: copy.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "206341627904"
                email: dhadiwalakash82@gmail.com
                executable: /Users/akashdhadiwal/Downloads/IE7374/IE7374-MLOps/.venv/bin/python
                git:
                    commit: b50d6d2d9cecde9f5705e039fcfbdea1b60d8c1a
                    remote: https://github.com/Akash-Dhadiwal/IE7374-MLOps.git
                host: Akashs-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/akashdhadiwal/Downloads/IE7374/IE7374-MLOps/Labs/Experiment_Tracking_Labs/W&B/copy.ipynb
                python: CPython 3.9.6
                root: /Users/akashdhadiwal/Downloads/IE7374/IE7374-MLOps/Labs/Experiment_Tracking_Labs/W&B
                startedAt: "2025-11-18T03:22:30.290331Z"
                writerId: vak1wl51xj58rdkyto11gecalprkyl36
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 3
                - 8
                - 13
                - 62
            "4": 3.9.6
            "5": 0.23.0
            "8":
                - 1
            "10":
                - 17
            "12": 0.23.0
            "13": darwin-arm64
